### PR TITLE
added new marker information

### PR DESCRIPTION
**Pull request by Kolshgamer**

### CODE REVIEW

**Comment by csauve** [comment]
Hey @Kolshgamer, thanks for the tip. As Galap mentioned on Discord this is not a hard-coded marker name so doesn't belong in the list you've added it to. Can you update the PR to add a new section or paragraph about commonly used marker names?

**Comment by Kolshgamer** [comment]
when i get home from school i will

**Comment by Kolshgamer** [comment]
@csauve What does PR stand for

**Comment by csauve** [comment]
PR stands for pull request. No worries, I clarified when merging this.

**Pull request merged**
